FROM ubuntu-ssh:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    vim \
    zsh \
    git \
    gdb \
    cmake \
    wget \
    curl \
    ca-certificates \
    unzip \
    xz-utils \
    build-essential \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*
