name: Build Ubuntu24 Dev Docker Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Show ubuntu24-dev directory
        run: |
          pwd
          ls -la ubuntu24-dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ubuntu24-dev
          file: ./ubuntu24-dev/Dockerfile.ssh
          push: true
          tags: ghcr.io/${{ github.actor }}/ubuntu-ssh:24.04

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ubuntu24-dev
          file: ./ubuntu24-dev/Dockerfile.dev
          push: true
          tags: ghcr.io/${{ github.actor }}/ubuntu-dev:24.04
